version: 2 
jobs:
  build:
    working_directory: ~/estimeo-highlights-sample2/ 
    docker:
      - image: circleci/node:4.8.2 
    steps:
      - checkout
      - run: sudo npm install -g npm@latest 
      - run: npm install
      - run: sudo npm install -g jest-cli
      - run: npm run build
      - run: npm run test